org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.java.home=C:\\Users\\koreshenko\\.jdks\\jdk-21.0.12+8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.overridePathCheck=true
kotlin.code.style=official
kotlin.incremental=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
